parameters:
    rs.form_handler.class: Reso\Bundle\FormBundle\FormHandler\FormHandler

services:
    rs.form_handler.factory:
        class: Reso\Bundle\FormBundle\FormHandler\Factory\FormHandlerFactory
        arguments: ['%rs.form_handler.class%']
        calls:
            - [setContainer, ['@service_container']]